### ISSUE TITLE
bug: Fails to build on zig 0.15.2 due to root module deprecation

### ISSUE THREAD

**Issue by jleskovar** [Raiden1411/zabi#156]
### Describe the bug

I'm trying to use zabi on zig 0.15.2, but fails to build with a swathe of issues such as:

```
~/.cache/zig/p/aio-0.0.0-776t3n5WBQASyyJ0vCpZxIX7U6NTVEvaWVf1-9sjcVYa/build.zig:75:14: error: no field named 'root_source_file' in struct 'Build.ExecutableOptions'
            .root_source_file = b.path("examples/" ++ @tagName(example) ++ ".zig"),
             ^~~~~~~~~~~~~~~~
```

```
~/.cache/zig/p/zabi-0.18.0-UB4phtC8SAADwr0BUfLzDsYfHCoprRJjjbQqmozAZqDs/build.zig:267:14: error: no field named 'root_source_file' in struct 'Build.TestOptions'
            .root_source_file = b.path("tests/root.zig"),
```

It looks like this is fixed on master, but master targets zig 0.16.x which is still in dev.

### Zig Version

0.15.2
